CompileFlags:                     # Tweak the parse settings
  Add: [-Wall]             # treat all files as C++, enable more warnings
#   Remove: [-W*, -std=gnu99]                     # strip all other warning-related flags
#   Compiler: clang++               # Change argv[0] of compile flags to `clang++`
