[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
nnoremap [Space]ps
      \ <Cmd>call dein#update()<CR>
nnoremap [Space]pc
      \ <Cmd>call dein#install()<CR>
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shirk/vim-gas'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'leafOfTree/vim-vue-plugin'

[[plugins]]
repo = 'rbtnn/vim-vimscript_indentexpr'

[[plugins]]
repo = 'mboughaba/i3config.vim'
hook_add = '''
autocmd MyAutoCmd BufNewFile,BufRead *i3/config set filetype=i3config
'''

# [[plugins]]
# repo = 'mhinz/vim-startify'

# [[plugins]]
# repo = 'rafi/awesome-vim-colorschemes'

# [[plugins]]
# repo = 'chriskempson/base16-vim'
#
# [[plugins]]
# repo = 'RRethy/nvim-base16'
#
# [[plugins]]
# repo = 'Mofiqul/vscode.nvim'
#

# colorschemes with treesitter support
[[plugins]]
repo = 'ChristianChiarulli/nvcode-color-schemes.vim'

[[plugins]]
repo = 'RRethy/nvim-base16'

[[plugins]]
repo = 'lourenci/github-colors'
