hooks_file = '$BASE_DIR/deinft.vim'

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
nnoremap [Space]ps
      \ <Cmd>call dein#update()<CR>
nnoremap [Space]pc
      \ <Cmd>call dein#install()<CR>
'''

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shirk/vim-gas'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'leafOfTree/vim-vue-plugin'

[[plugins]]
repo = 'rbtnn/vim-vimscript_indentexpr'
# colorschemes with treesitter support
[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'Th3Whit3Wolf/one-nvim'

[[plugins]]
repo = 'mhinz/vim-janah'

[[plugins]]
repo = 'NTBBloodbath/doom-one.nvim'
